### ISSUE TITLE
khan depends on packages that no longer exist

### ISSUE THREAD

**Issue by cebukin** [topfreegames/khan#33]
When trying to install khan I get the following errors:  

`package github.com/labstack/echo/engine: cannot find package "github.com/labstack/echo/engine" in any of:
	/usr/local/opt/go/libexec/src/github.com/labstack/echo/engine (from $GOROOT)
	/Users/cebukin/go/src/github.com/labstack/echo/engine (from $GOPATH)
package github.com/labstack/echo/engine/fasthttp: cannot find package "github.com/labstack/echo/engine/fasthttp" in any of:
	/usr/local/opt/go/libexec/src/github.com/labstack/echo/engine/fasthttp (from $GOROOT)
	/Users/cebukin/go/src/github.com/labstack/echo/engine/fasthttp (from $GOPATH)
package github.com/labstack/echo/engine/standard: cannot find package "github.com/labstack/echo/engine/standard" in any of:
	/usr/local/opt/go/libexec/src/github.com/labstack/echo/engine/standard (from $GOROOT)
	/Users/cebukin/go/src/github.com/labstack/echo/engine/standard (from $GOPATH)
package github.com/uber-go/zap: code in directory /Users/cebukin/go/src/github.com/uber-go/zap expects import "go.uber.org/zap"`

It seems like it is depending on packages that no longer exist

**Comment by matheuscscp** [comment]
How did you proceed to get this error?

**Comment by leonardo2204** [comment]
I know this is [very] old, we are migrating Khan from deps to modules and we will have a working version in a couple of weeks
